### PR TITLE
Object class initialization (for 1.4.2)

### PR DESCRIPTION
**Pull request by DanPlayz0**
Redone the PR for version 1.4.2's rewrite/changes.

Allow users to create a card via an object like
```js
const card = new musicCard({
  name: "Makeba (Ian Asher Remix)",
  author: "By Ian Asher",
  color: "auto", // or hex color without # (default: auto) (auto: dominant color from thumbnail)
  brightness: 50,
  thumbnail: "https://indexmusic.it/wp-content/uploads/2023/07/jain-makeba-ian-asher-remix.jpg",
  progress: 0,
  startTime: "0:00",
  endTime: "3:00"
})
```

### CODE REVIEW

**Review by UnschooledGamer — APPROVED** [review]
All Good!

**Comment by UnschooledGamer** [comment]
@DanPlayz0 I think **startTime** looks better instead of start_time and **endTime** better than end_time.

What is your opinion on this?
I'll successfully merge this after your answer 😄

**Comment by DanPlayz0** [comment]
I'm just used to using lower snake case and that's something I tend to see used for objects. 

Though if you'd like I'll update it to use `startTime` rather than `start_time` and `endTime` rather than `end_time`.

**Comment by flam3face** [comment]
@DanPlayz0 For sure, I will make this change. The problem is that I have published the new version recently, so until the next new feature, I can't change constructor one.

**Comment by Drago09t** [comment]
why its not moving time

**Review by Elitex07 — APPROVED** [review]
Looks cool.

**Pull request merged**
