### PR TITLE
Enhancements and Code Fixes: Constructor Parameters, JSDoc, Time Validation, Color Support, and Style Compliance

### PR DESCRIPTION
**Pull request by codeblitz97**
In this pull request, I've added some features and fixed some issues.

## Added:
- Added parameters on the constructor
- Added JSDoc for better intelligence purpose
- Create time checking function that will check if the time is on valid format or not
- Added time checking
- Add support for "random" color in `colorFetch()` method

## Fixed:
- Fixed class name with it's rules (https://github.com/felixge/node-style-guide#user-content-use-uppercamelcase-for-class-names)
- Reformated the code

### CODE REVIEW

**Comment by Elitex07** [comment]
@codeblitz97 After checking the code, am not able to find anything, which should be merged into the repository. Can you define any?

**Comment by codeblitz97** [comment]
I've added JSDoc for VSCode intelligence (https://jsdoc.app/) it's just comments but it provides intelligence to the VSCode and maybe for other code editors too, then I saw that the class name actually doesn't follow the rules of naming class, so I've changed "musicCard" to "MusicCard" then for making things easier, I've added an object in the main class which has all of the options. For utility, I've added "random" options in the `colorFetch()` method so we can use:
color: "random" in the class object or the class method. Also created an interface for typescript. Last, for error handling I've created a new method that will check if the provided "endtime" or "starttime" is in the format: "min:seconds (0:00 or whatever)" or not, it will throw an error if the time is not in the valid format

**Comment by Elitex07** [comment]
@codeblitz97 am asking again. Tell things which should be merged.

**Comment by codeblitz97** [comment]
@Elitex07 https://github.com/a3pire/musicard/pull/12#issuecomment-1737694580

**Comment by Elitex07** [comment]
- Only adding spaces will not be considered.
- Intelligence TS is contradictory to what we already have
- Class constructor declaration is also contradictory to what we already have
- We don't want a release with breaking changes, which do not add anything valuable to the repository

**Comment by Elitex07** [comment]
After this, if you have anything which should be merged, like the error handling of time formats. You should create another pull request with only those changes.

**Comment by Elitex07** [comment]
Kind of yea.

**Comment by codeblitz97** [comment]
Okay then, removing everything except time checking, and those spaces were added by my formatter (prettier) automatically so I had no control over that

**Comment by Elitex07** [comment]
np

**Comment by codeblitz97** [comment]
Updated

**Comment by flameface** [comment]
@codeblitz97 I appreciate your work, and I want to make things clear.

Before you, one guy already sent that class thing to be direct in **musicard({ here })**, which I just denied because we can't change it as it's our way of presenting it, and we can't change it directly now.
 
You are saying somewhat about the rules of classes. It's **musicCard** or **MusicCard** doesn't matter; I checked the source, and they want to say it shouldn't be **music_Card**

Last, the time formatting; it's a canvas card; you can do whatever you want; there are no restrictions; and it's not required for now, i think.

**Comment by codeblitz97** [comment]
@flameface Yeah, I understand but for the time formatting, will it still work if I provide something like: "oneminute:fiveseconds" or whatever? I don't think so prevent that I've added that

**Comment by flameface** [comment]
I like the time formatting, I will check and let you tomorrow. thank you

**Comment by flameface** [comment]
> @flameface Yeah, I understand but for the time formatting, will it still work if I provide something like: "oneminute:fiveseconds" or whatever? I don't think so prevent that I've added that

It will be okay, but till now, I didn't see anyone do that.

**Comment by Elitex07** [comment]
fr 💀

**Comment by codeblitz97** [comment]
@Elitex07 Added package.json and I'm closing this pull but I'm working on something else

**Comment by flameface** [comment]
All is good to go.

**Comment by flameface** [comment]
All is good to go.

**Comment by flameface** [comment]
will you pull the request again of that time formatting

**Comment by codeblitz97** [comment]
Sure

**Pull request closed without merging**
